#ifndef EV_ATB_THERMO_WEMOS_ESP_WROOM_02_4MB_BOARD_PROFILE_H
#define EV_ATB_THERMO_WEMOS_ESP_WROOM_02_4MB_BOARD_PROFILE_H

#include "ev/compiler.h"
#include "ev/oled_actor.h"
#include "ev/bh1750_driver.h"
#include "ev/supervisor_actor.h"

#define EV_BOARD_PROFILE_TAG "ev_atbthermo"
#define EV_BOARD_PROFILE_NAME "atb_thermo_wemos_esp_wroom_02_4mb"
#define EV_BOARD_HAS_I2C0 1U
#define EV_BOARD_HAS_ONEWIRE0 1U
#define EV_BOARD_HAS_GPIO_IRQ 0U
#define EV_BOARD_HAS_DEEP_SLEEP_WAKE_GPIO16 0U
#ifndef EV_BOARD_HAS_BH1750
#define EV_BOARD_HAS_BH1750 1U
#endif
#ifndef EV_BOARD_HAS_OLED
#define EV_BOARD_HAS_OLED 1U
#endif
#define EV_BOARD_HAS_WDT 0U
#ifndef EV_BOARD_HAS_NET
#define EV_BOARD_HAS_NET 0U
#endif
#define EV_BOARD_WDT_TIMEOUT_MS 3000U
#define EV_BOARD_RUNTIME_PROFILE_MINIMAL 0U
#define EV_BOARD_RUNTIME_PROFILE_FULL 1U

#define EV_BOARD_NET_WIFI_AUTH_OPEN 0U
#define EV_BOARD_NET_WIFI_AUTH_WPA2_PSK 1U

#ifdef EV_BOARD_INCLUDE_LOCAL_SECRETS
#include "board_secrets.local.h"
#endif

#ifndef EV_BOARD_NET_WIFI_SSID
#define EV_BOARD_NET_WIFI_SSID ""
#endif

#ifndef EV_BOARD_NET_WIFI_PASSWORD
#define EV_BOARD_NET_WIFI_PASSWORD ""
#endif

#ifndef EV_BOARD_NET_WIFI_AUTH_MODE
#define EV_BOARD_NET_WIFI_AUTH_MODE EV_BOARD_NET_WIFI_AUTH_WPA2_PSK
#endif

#ifndef EV_BOARD_NET_WIFI_SECURITY_LABEL
#define EV_BOARD_NET_WIFI_SECURITY_LABEL "WPA2-PSK"
#endif

#ifndef EV_BOARD_NET_MQTT_BROKER_URI
#define EV_BOARD_NET_MQTT_BROKER_URI ""
#endif

#ifndef EV_BOARD_NET_MQTT_CLIENT_ID
#define EV_BOARD_NET_MQTT_CLIENT_ID EV_BOARD_PROFILE_TAG
#endif

#ifndef EV_BOARD_NET_COMMAND_TOKEN
#define EV_BOARD_NET_COMMAND_TOKEN ""
#endif

#ifndef EV_BOARD_REMOTE_COMMAND_CAPABILITIES
#define EV_BOARD_REMOTE_COMMAND_CAPABILITIES 0U
#endif

enum {
#define EV_BSP_PIN(name, gpio, desc) EV_BOARD_##name = (gpio),
#define EV_BSP_PIN_ANALOG(name, desc)
#include "pins.def"
#undef EV_BSP_PIN
#undef EV_BSP_PIN_ANALOG
};

#define EV_BOARD_I2C_SCL_GPIO EV_BOARD_PIN_I2C0_SCL
#define EV_BOARD_I2C_SDA_GPIO EV_BOARD_PIN_I2C0_SDA
#define EV_BOARD_ONEWIRE_GPIO EV_BOARD_PIN_ONEWIRE0_DQ
#define EV_BOARD_PWR_CTRL_GPIO EV_BOARD_PIN_PWR_CTRL
#define EV_BOARD_STATUS_LED_GPIO EV_BOARD_PIN_STATUS_LED
#define EV_BOARD_PIR_CHECK_GPIO EV_BOARD_PIN_PIR_CHECK
#define EV_BOARD_AUDIO_GPIO EV_BOARD_PIN_AUDIO
#define EV_BOARD_PIR_DIS_GPIO EV_BOARD_PIN_PIR_DIS

#define EV_BOARD_I2C_SPEED_SAFE_HZ 100000U
#define EV_BOARD_I2C_SPEED_FAST_HZ 400000U
#define EV_BOARD_I2C_DEFAULT_SPEED_HZ EV_BOARD_I2C_SPEED_SAFE_HZ
#define EV_BOARD_I2C_FAST_400KHZ_REQUIRES_HIL 1U

#define EV_BOARD_RTC_ADDR_7BIT 0U
#define EV_BOARD_MCP23008_ADDR_7BIT 0U
#define EV_BOARD_OLED_ADDR_7BIT 0x3CU
#ifndef EV_BOARD_BH1750_ADDR_7BIT
#define EV_BOARD_BH1750_ADDR_7BIT 0x23U
#endif
#define EV_BOARD_BH1750_ALT_ADDR_7BIT 0x5CU
#define EV_BOARD_BME280_BMP180_ADDR_7BIT 0x76U
#define EV_BOARD_BME280_BMP180_ALT_ADDR_7BIT 0x77U
#define EV_BOARD_OLED_CONTROLLER EV_OLED_CONTROLLER_SSD1306_128X64
#define EV_BOARD_RTC_SQW_LINE_ID 0U

#ifndef EV_ATB_THERMO_ENABLE_PERIPH_POWER_CONTROL
#define EV_ATB_THERMO_ENABLE_PERIPH_POWER_CONTROL 1U
#endif
#ifndef EV_ATB_THERMO_PWR_CTRL_ACTIVE_LOW
#define EV_ATB_THERMO_PWR_CTRL_ACTIVE_LOW 1U
#endif
#ifndef EV_ATB_THERMO_PERIPH_STABILIZE_MS
#define EV_ATB_THERMO_PERIPH_STABILIZE_MS 20U
#endif

#define EV_BOARD_RUNTIME_HARDWARE_PRESENT_MASK \
    (EV_SUPERVISOR_HW_DS18B20 | \
     ((EV_BOARD_HAS_BH1750 != 0U) ? EV_SUPERVISOR_HW_BH1750 : 0U) | \
     ((EV_BOARD_HAS_OLED != 0U) ? EV_SUPERVISOR_HW_OLED : 0U))
#define EV_BOARD_SUPERVISOR_REQUIRED_MASK 0U
#define EV_BOARD_SUPERVISOR_OPTIONAL_MASK EV_BOARD_RUNTIME_HARDWARE_PRESENT_MASK

EV_STATIC_ASSERT(EV_BOARD_I2C_SCL_GPIO == 5U, "ATB THERMO SCL must remain GPIO5/D1");
EV_STATIC_ASSERT(EV_BOARD_I2C_SDA_GPIO == 4U, "ATB THERMO SDA must remain GPIO4/D2");
EV_STATIC_ASSERT(EV_BOARD_ONEWIRE_GPIO == 13U, "ATB THERMO DS18B20 DQ must remain GPIO13/D7");
EV_STATIC_ASSERT(EV_BOARD_PWR_CTRL_GPIO == 0U, "ATB THERMO PWR_CTRL must remain GPIO0/D3 boot-strap pin");
EV_STATIC_ASSERT(EV_BOARD_STATUS_LED_GPIO == 2U, "ATB THERMO LED must remain GPIO2/D4 active-low");
EV_STATIC_ASSERT(EV_BOARD_PIR_CHECK_GPIO == 14U, "ATB THERMO PIR_CHECK must remain GPIO14/D5");
EV_STATIC_ASSERT(EV_BOARD_AUDIO_GPIO == 12U, "ATB THERMO AUDIO must remain GPIO12/D6");
EV_STATIC_ASSERT(EV_BOARD_PIR_DIS_GPIO == 15U, "ATB THERMO PIR_DIS must remain GPIO15/D8");

#endif /* EV_ATB_THERMO_WEMOS_ESP_WROOM_02_4MB_BOARD_PROFILE_H */
