#ifndef EV_WEMOS_ESP_WROOM_02_18650_BOARD_SECRETS_EXAMPLE_H
#define EV_WEMOS_ESP_WROOM_02_18650_BOARD_SECRETS_EXAMPLE_H

/*
 * Copy this file to board_secrets.local.h to enable WiFi for this target.
 * The local file is ignored by git. Do not put real credentials in this example.
 */
#undef EV_BOARD_HAS_NET
#define EV_BOARD_HAS_NET 1U

#undef EV_BOARD_NET_WIFI_SSID
#define EV_BOARD_NET_WIFI_SSID "your-2g4-ssid"

#undef EV_BOARD_NET_WIFI_PASSWORD
#define EV_BOARD_NET_WIFI_PASSWORD "your-password"

#undef EV_BOARD_NET_WIFI_AUTH_MODE
#define EV_BOARD_NET_WIFI_AUTH_MODE EV_BOARD_NET_WIFI_AUTH_WPA2_PSK

#undef EV_BOARD_NET_WIFI_SECURITY_LABEL
#define EV_BOARD_NET_WIFI_SECURITY_LABEL "WPA2-PSK"

#undef EV_BOARD_NET_MQTT_BROKER_URI
#define EV_BOARD_NET_MQTT_BROKER_URI ""

#undef EV_BOARD_NET_MQTT_CLIENT_ID
#define EV_BOARD_NET_MQTT_CLIENT_ID "ev_wroom02"

#undef EV_BOARD_NET_COMMAND_TOKEN
#define EV_BOARD_NET_COMMAND_TOKEN ""

#undef EV_BOARD_REMOTE_COMMAND_CAPABILITIES
#define EV_BOARD_REMOTE_COMMAND_CAPABILITIES 0U

#endif /* EV_WEMOS_ESP_WROOM_02_18650_BOARD_SECRETS_EXAMPLE_H */
