#ifndef EV_WEMOS_ESP_WROOM_02_18650_BOARD_PROFILE_H
#define EV_WEMOS_ESP_WROOM_02_18650_BOARD_PROFILE_H

#include "ev/compiler.h"
#include "ev/oled_actor.h"
#include "ev/supervisor_actor.h"

#define EV_BOARD_PROFILE_TAG "ev_wroom02"
#define EV_BOARD_PROFILE_NAME "wemos_esp_wroom_02_18650"
#define EV_BOARD_HAS_I2C0 1U
#define EV_BOARD_HAS_ONEWIRE0 0U
#define EV_BOARD_HAS_GPIO_IRQ 0U
#define EV_BOARD_HAS_DEEP_SLEEP_WAKE_GPIO16 1U
#define EV_BOARD_HAS_WDT 0U
#ifndef EV_BOARD_HAS_NET
#define EV_BOARD_HAS_NET 0U
#endif
#define EV_BOARD_WDT_TIMEOUT_MS 3000U
#define EV_BOARD_RUNTIME_PROFILE_BOOT_DIAG 1U
#define EV_BOARD_RUNTIME_PROFILE_MINIMAL 1U
#define EV_BOARD_RUNTIME_PROFILE_FULL 0U

#define EV_BOARD_NET_WIFI_AUTH_OPEN 0U
#define EV_BOARD_NET_WIFI_AUTH_WPA2_PSK 1U

#ifdef EV_BOARD_INCLUDE_LOCAL_SECRETS
#include "board_secrets.local.h"
#endif

#ifndef EV_BOARD_NET_WIFI_SSID
#define EV_BOARD_NET_WIFI_SSID ""
#endif

#ifndef EV_BOARD_NET_WIFI_PASSWORD
#define EV_BOARD_NET_WIFI_PASSWORD ""
#endif

#ifndef EV_BOARD_NET_WIFI_AUTH_MODE
#define EV_BOARD_NET_WIFI_AUTH_MODE EV_BOARD_NET_WIFI_AUTH_WPA2_PSK
#endif

#ifndef EV_BOARD_NET_WIFI_SECURITY_LABEL
#define EV_BOARD_NET_WIFI_SECURITY_LABEL "WPA2-PSK"
#endif

#ifndef EV_BOARD_NET_MQTT_BROKER_URI
#define EV_BOARD_NET_MQTT_BROKER_URI ""
#endif

#ifndef EV_BOARD_NET_MQTT_CLIENT_ID
#define EV_BOARD_NET_MQTT_CLIENT_ID EV_BOARD_PROFILE_TAG
#endif

#ifndef EV_BOARD_NET_COMMAND_TOKEN
#define EV_BOARD_NET_COMMAND_TOKEN ""
#endif

#ifndef EV_BOARD_REMOTE_COMMAND_CAPABILITIES
#define EV_BOARD_REMOTE_COMMAND_CAPABILITIES 0U
#endif

enum {
#define EV_BSP_PIN(name, gpio, desc) EV_BOARD_##name = (gpio),
#define EV_BSP_PIN_ANALOG(name, desc)
#include "pins.def"
#undef EV_BSP_PIN
#undef EV_BSP_PIN_ANALOG
};

#define EV_BOARD_I2C_SCL_GPIO EV_BOARD_PIN_OPTIONAL_I2C0_SCL
#define EV_BOARD_I2C_SDA_GPIO EV_BOARD_PIN_OPTIONAL_I2C0_SDA
#define EV_BOARD_WAKE_GPIO EV_BOARD_PIN_STATUS_LED
#define EV_BOARD_RTC_ADDR_7BIT 0U
#define EV_BOARD_MCP23008_ADDR_7BIT 0U
#define EV_BOARD_OLED_ADDR_7BIT 0U
#define EV_BOARD_OLED_CONTROLLER EV_OLED_CONTROLLER_SSD1306
#define EV_BOARD_RTC_SQW_LINE_ID 0U
#define EV_BOARD_RUNTIME_HARDWARE_PRESENT_MASK 0U
#define EV_BOARD_SUPERVISOR_REQUIRED_MASK 0U
#define EV_BOARD_SUPERVISOR_OPTIONAL_MASK 0U

#endif /* EV_WEMOS_ESP_WROOM_02_18650_BOARD_PROFILE_H */
