COMPONENT_SRCDIRS := .
COMPONENT_ADD_INCLUDEDIRS := . ../../../../../bsp/atnel_air_esp_motherboard
COMPONENT_REQUIRES := ev_platform
CFLAGS += -DEV_HIL_ONEWIRE_IRQ=1 \
    -DEV_BOARD_HIL_ONEWIRE_READS=4 \
    -DEV_BOARD_HIL_IRQ_FLOOD_OUTPUT_GPIO=15 \
    -DEV_BOARD_HIL_IRQ_FLOOD_LINE_ID=0
