#!/usr/bin/env python3
"""Create ignored board_secrets.local.h files for WiFi-capable ESP8266 targets.

The tool intentionally writes only developer-local files ignored by git.  It does
not modify tracked BSP headers and it never prints the WiFi password.
"""
from __future__ import annotations

import argparse
import getpass
import json
import os
from pathlib import Path
import stat
import sys
from tempfile import NamedTemporaryFile

ROOT = Path(__file__).resolve().parents[1]

BOARD_TARGETS: dict[str, dict[str, str]] = {
    "atnel": {
        "board_dir": "bsp/atnel_air_esp_motherboard",
        "guard": "EV_ATNEL_AIR_BOARD_SECRETS_LOCAL_H",
        "client_id": "ev_atnel",
        "display": "ATNEL AIR ESP Motherboard",
    },
    "wemos": {
        "board_dir": "bsp/wemos_esp_wroom_02_18650",
        "guard": "EV_WEMOS_ESP_WROOM_02_18650_BOARD_SECRETS_LOCAL_H",
        "client_id": "ev_wroom02",
        "display": "Wemos ESP-WROOM-02 18650",
    },
}

AUTH_MODES = {
    "wpa2": "EV_BOARD_NET_WIFI_AUTH_WPA2_PSK",
    "open": "EV_BOARD_NET_WIFI_AUTH_OPEN",
}


def c_string(value: str) -> str:
    return json.dumps(value)


def target_names(raw: str) -> list[str]:
    if raw == "all":
        return list(BOARD_TARGETS.keys())
    names = [item.strip() for item in raw.split(",") if item.strip()]
    unknown = [name for name in names if name not in BOARD_TARGETS]
    if unknown:
        raise ValueError(f"unknown target(s): {', '.join(unknown)}")
    return names


def secret_path(target: str) -> Path:
    return ROOT / BOARD_TARGETS[target]["board_dir"] / "board_secrets.local.h"


def render_header(target: str, ssid: str, password: str, auth_mode: str, mqtt_uri: str, command_token: str) -> str:
    meta = BOARD_TARGETS[target]
    auth_macro = AUTH_MODES[auth_mode]
    security_label = "open" if auth_mode == "open" else "WPA2-PSK"
    lines = [
        f"#ifndef {meta['guard']}",
        f"#define {meta['guard']}",
        "",
        "/*",
        " * Developer-local WiFi credentials for this board profile.",
        " * This file is generated by tools/wifi_secrets.py and is ignored by git.",
        " * Do not commit this file or paste its content into issue trackers/logs.",
        " */",
        "",
        "#undef EV_BOARD_HAS_NET",
        "#define EV_BOARD_HAS_NET 1U",
        "",
        "#undef EV_BOARD_NET_WIFI_SSID",
        f"#define EV_BOARD_NET_WIFI_SSID {c_string(ssid)}",
        "",
        "#undef EV_BOARD_NET_WIFI_PASSWORD",
        f"#define EV_BOARD_NET_WIFI_PASSWORD {c_string(password)}",
        "",
        "#undef EV_BOARD_NET_WIFI_AUTH_MODE",
        f"#define EV_BOARD_NET_WIFI_AUTH_MODE {auth_macro}",
        "",
        "#undef EV_BOARD_NET_WIFI_SECURITY_LABEL",
        f"#define EV_BOARD_NET_WIFI_SECURITY_LABEL {c_string(security_label)}",
        "",
        "#undef EV_BOARD_NET_MQTT_BROKER_URI",
        f"#define EV_BOARD_NET_MQTT_BROKER_URI {c_string(mqtt_uri)}",
        "",
        "#undef EV_BOARD_NET_MQTT_CLIENT_ID",
        f"#define EV_BOARD_NET_MQTT_CLIENT_ID {c_string(meta['client_id'])}",
        "",
        "#undef EV_BOARD_NET_COMMAND_TOKEN",
        f"#define EV_BOARD_NET_COMMAND_TOKEN {c_string(command_token)}",
        "",
        "#undef EV_BOARD_REMOTE_COMMAND_CAPABILITIES",
        "#define EV_BOARD_REMOTE_COMMAND_CAPABILITIES 0U",
        "",
        f"#endif /* {meta['guard']} */",
        "",
    ]
    return "\n".join(lines)


def write_secret(path: Path, text: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} exists; pass --force to overwrite")
    path.parent.mkdir(parents=True, exist_ok=True)
    with NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as tmp:
        tmp.write(text)
        tmp_path = Path(tmp.name)
    os.chmod(tmp_path, stat.S_IRUSR | stat.S_IWUSR)
    tmp_path.replace(path)
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def read_password(args: argparse.Namespace) -> str:
    if args.password_env:
        value = os.environ.get(args.password_env)
        if value is None:
            raise RuntimeError(f"environment variable {args.password_env} is not set")
        return value
    if args.password_file:
        return Path(args.password_file).read_text(encoding="utf-8").rstrip("\r\n")
    if args.password_stdin:
        return sys.stdin.read().rstrip("\r\n")
    if args.password:
        return args.password
    return getpass.getpass("WiFi password: ")


def command_write(args: argparse.Namespace) -> int:
    names = target_names(args.target)
    password = read_password(args)
    if not args.ssid:
        raise RuntimeError("--ssid must not be empty")
    if args.auth == "wpa2" and not password:
        raise RuntimeError("WPA2 password must not be empty")
    for name in names:
        path = secret_path(name)
        text = render_header(name, args.ssid, password, args.auth, args.mqtt_uri, args.command_token)
        write_secret(path, text, args.force)
        print(f"wrote {path.relative_to(ROOT)} for {BOARD_TARGETS[name]['display']} (password not printed)")
    return 0


def command_status(args: argparse.Namespace) -> int:
    names = target_names(args.target)
    for name in names:
        path = secret_path(name)
        if path.exists():
            mode = stat.S_IMODE(path.stat().st_mode)
            print(f"{name}: present path={path.relative_to(ROOT)} mode={mode:04o}")
        else:
            print(f"{name}: missing path={path.relative_to(ROOT)}")
    return 0


def self_test() -> int:
    sample = render_header("wemos", "ssid", "pa\\\"ss", "wpa2", "", "")
    assert "EV_BOARD_HAS_NET 1U" in sample
    assert "EV_BOARD_NET_WIFI_SSID \"ssid\"" in sample
    assert "pa\\\\\\\"ss" in sample
    assert target_names("all") == ["atnel", "wemos"]
    print("EV_WIFI_SECRETS_SELF_TEST PASS")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Create local ignored WiFi board_secrets.local.h files")
    parser.add_argument("--self-test", action="store_true", help="run parser/rendering self-test and exit")
    sub = parser.add_subparsers(dest="cmd")

    write = sub.add_parser("write", help="write local board_secrets.local.h")
    write.add_argument("--target", default="all", help="atnel, wemos, all, or comma-separated list")
    write.add_argument("--ssid", required=True, help="2.4 GHz WiFi SSID")
    write.add_argument("--password", help="WiFi password; prefer --password-env or prompt for privacy")
    write.add_argument("--password-env", help="read WiFi password from named environment variable")
    write.add_argument("--password-file", help="read WiFi password from file")
    write.add_argument("--password-stdin", action="store_true", help="read WiFi password from stdin")
    write.add_argument("--auth", choices=sorted(AUTH_MODES), default="wpa2")
    write.add_argument("--mqtt-uri", default="", help="optional MQTT broker URI")
    write.add_argument("--command-token", default="", help="optional remote command token")
    write.add_argument("--force", action="store_true", help="overwrite existing local secrets")
    write.set_defaults(func=command_write)

    status = sub.add_parser("status", help="show whether local secrets exist")
    status.add_argument("--target", default="all", help="atnel, wemos, all, or comma-separated list")
    status.set_defaults(func=command_status)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    if args.self_test:
        return self_test()
    if not hasattr(args, "func"):
        parser.print_help()
        return 2
    try:
        return args.func(args)
    except Exception as exc:  # keep CLI errors deterministic and readable
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
