#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path
from collections import defaultdict

RE_EVENT = re.compile(
    r'^\s*EV_EVENT\(\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*"([^"]*)"\s*\)\s*$'
)
RE_ACTOR = re.compile(
    r'^\s*EV_ACTOR\(\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*([0-9]+U?)\s*,\s*"([^"]*)"\s*\)\s*$'
)
RE_ROUTE = re.compile(
    r'^\s*EV_ROUTE\(\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*\)\s*$'
)
RE_ROUTE_EX = re.compile(
    r'^\s*EV_ROUTE_EX\(\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*([A-Z0-9_]+)\s*,\s*([^,]+)\s*,\s*([^)]+)\s*\)\s*$'
)

ROOT = Path(__file__).resolve().parents[2]
CONFIG_DIR = ROOT / "config"
OUT_PATH = ROOT / "core" / "generated" / "include" / "ev" / "route_table_generated.h"


def read_catalog_lines(path: Path) -> list[str]:
    lines: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("//") or line.startswith("#"):
            continue
        lines.append(line)
    return lines


def parse_events(path: Path) -> list[str]:
    events: list[str] = []
    for line in read_catalog_lines(path):
        match = RE_EVENT.match(line)
        if match is None:
            raise ValueError(f"invalid event definition in {path}: {line}")
        events.append(match.group(1))
    return events


def parse_actors(path: Path) -> list[str]:
    actors: list[str] = []
    for line in read_catalog_lines(path):
        match = RE_ACTOR.match(line)
        if match is None:
            raise ValueError(f"invalid actor definition in {path}: {line}")
        actors.append(match.group(1))
    return actors


def parse_routes(path: Path, events: set[str], actors: set[str]) -> list[tuple[str, str, str, str, str]]:
    routes: list[tuple[str, str, str, str, str]] = []
    seen: set[tuple[str, str]] = set()
    for line in read_catalog_lines(path):
        match_ex = RE_ROUTE_EX.match(line)
        match = RE_ROUTE.match(line)
        if match_ex is not None:
            event, actor, qos, priority, flags = (x.strip() for x in match_ex.groups())
        elif match is not None:
            event, actor = (x.strip() for x in match.groups())
            qos, priority, flags = "EV_ROUTE_QOS_CRITICAL", "0U", "0U"
        else:
            raise ValueError(f"invalid route definition in {path}: {line}")
        if event not in events:
            raise ValueError(f"route references unknown event {event}")
        if actor not in actors:
            raise ValueError(f"route references unknown actor {actor}")
        key = (event, actor)
        if key in seen:
            raise ValueError(f"duplicate route {event}->{actor}")
        seen.add(key)
        routes.append((event, actor, qos, priority, flags))
    return routes


def main() -> None:
    events = parse_events(CONFIG_DIR / "events.def")
    actors = parse_actors(CONFIG_DIR / "actors.def")
    routes = parse_routes(CONFIG_DIR / "routes.def", set(events), set(actors))

    by_event: dict[str, list[tuple[str, str, str, str, str]]] = defaultdict(list)
    for route in routes:
        by_event[route[0]].append(route)

    ordered: list[tuple[str, str, str, str, str]] = []
    spans: dict[str, tuple[int, int]] = {}
    for event in events:
        start = len(ordered)
        ordered.extend(by_event.get(event, []))
        count = len(ordered) - start
        if count:
            spans[event] = (start, count)

    out = []
    out.append("/* Auto-generated by tools/routegen/routegen.py.\n")
    out.append(" * Source of truth: config/routes.def.\n")
    out.append(" * Do not edit manually; run make routegen.\n")
    out.append(" */\n")
    out.append("#ifndef EV_ROUTE_TABLE_GENERATED_H\n")
    out.append("#define EV_ROUTE_TABLE_GENERATED_H\n\n")
    out.append('#include "ev/route_table.h"\n\n')
    out.append(f"#define EV_ROUTE_TABLE_GENERATED_COUNT {len(ordered)}U\n\n")
    out.append("enum {\n")
    for event, actor, _qos, _priority, _flags in ordered:
        out.append(f"    EV_ROUTE_UNIQUE__{event}__{actor} = 1,\n")
    out.append("    EV_ROUTE_UNIQUE__SENTINEL = 0\n")
    out.append("};\n\n")
    out.append("static const ev_route_t k_ev_route_table_generated[] = {\n")
    for event, actor, qos, priority, flags in ordered:
        out.append(f"    {{ {event}, {actor}, {qos}, (uint8_t)({priority}), (uint32_t)({flags}) }},\n")
    out.append("};\n\n")
    out.append("static const ev_route_span_t k_ev_route_spans_generated[EV_EVENT_COUNT] = {\n")
    for event in events:
        if event in spans:
            start, count = spans[event]
            out.append(f"    [{event}] = {{ {start}U, {count}U }},\n")
    out.append("};\n\n")
    out.append("#endif /* EV_ROUTE_TABLE_GENERATED_H */\n")
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("".join(out), encoding="utf-8")
    print(f"generated {len(ordered)} routes into {OUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
