#ifndef EV_ATNEL_AIR_BOARD_PROFILE_H
#define EV_ATNEL_AIR_BOARD_PROFILE_H
#include "ev/compiler.h"
#include "ev/oled_actor.h"
#include "ev/supervisor_actor.h"

#define EV_BOARD_PROFILE_TAG "ev_atnel"
#define EV_BOARD_PROFILE_NAME "atnel_air_esp_motherboard"
#define EV_BOARD_HAS_I2C0 1U
#define EV_BOARD_HAS_ONEWIRE0 1U
#define EV_BOARD_HAS_GPIO_IRQ 1U
#define EV_BOARD_HAS_DEEP_SLEEP_WAKE_GPIO16 0U
#define EV_BOARD_HAS_WDT 0U
#define EV_BOARD_WDT_TIMEOUT_MS 3000U

#define EV_BOARD_NET_WIFI_AUTH_OPEN 0U
#define EV_BOARD_NET_WIFI_AUTH_WPA2_PSK 1U

/*
 * Optional private network credentials.  Tracked BSP files intentionally keep
 * WiFi/MQTT credentials empty.  Define EV_BOARD_INCLUDE_LOCAL_SECRETS and place
 * a developer-local board_secrets.local.h next to this file, or provide -D
 * overrides from the build environment.  The local header is ignored by git.
 */
#if defined(EV_BOARD_INCLUDE_LOCAL_SECRETS)
#include "board_secrets.local.h"
#endif

#ifndef EV_BOARD_HAS_NET
#define EV_BOARD_HAS_NET 0U
#endif

#ifndef EV_BOARD_NET_WIFI_SSID
#define EV_BOARD_NET_WIFI_SSID ""
#endif

#ifndef EV_BOARD_NET_WIFI_PASSWORD
#define EV_BOARD_NET_WIFI_PASSWORD ""
#endif

#ifndef EV_BOARD_NET_WIFI_AUTH_MODE
#define EV_BOARD_NET_WIFI_AUTH_MODE EV_BOARD_NET_WIFI_AUTH_WPA2_PSK
#endif

#ifndef EV_BOARD_NET_WIFI_SECURITY_LABEL
#define EV_BOARD_NET_WIFI_SECURITY_LABEL "WPA2-PSK"
#endif

#ifndef EV_BOARD_NET_MQTT_BROKER_URI
#define EV_BOARD_NET_MQTT_BROKER_URI ""
#endif

#ifndef EV_BOARD_NET_MQTT_CLIENT_ID
#define EV_BOARD_NET_MQTT_CLIENT_ID EV_BOARD_PROFILE_TAG
#endif

#ifndef EV_BOARD_NET_COMMAND_TOKEN
#define EV_BOARD_NET_COMMAND_TOKEN ""
#endif

#ifndef EV_BOARD_REMOTE_COMMAND_CAPABILITIES
#define EV_BOARD_REMOTE_COMMAND_CAPABILITIES 0U
#endif
enum {
#define EV_BSP_PIN(name, gpio, desc) EV_BOARD_##name = (gpio),
#define EV_BSP_PIN_ANALOG(name, desc)
#include "pins.def"
#undef EV_BSP_PIN
#undef EV_BSP_PIN_ANALOG
};
#define EV_BOARD_I2C_SCL_GPIO       EV_BOARD_PIN_I2C0_SCL
#define EV_BOARD_I2C_SDA_GPIO       EV_BOARD_PIN_I2C0_SDA
#define EV_BOARD_ONEWIRE_GPIO       EV_BOARD_PIN_ONEWIRE0_DQ
#define EV_BOARD_IRQ_IR0_GPIO       EV_BOARD_PIN_OPTIONAL_IR0_DATA
#define EV_BOARD_IRQ_INT0_GPIO      EV_BOARD_PIN_OPTIONAL_INT0
#define EV_BOARD_RTC_ADDR_7BIT      0x68U
#define EV_BOARD_MCP23008_ADDR_7BIT 0x20U
#define EV_BOARD_OLED_ADDR_7BIT     0x3CU
#define EV_BOARD_OLED_CONTROLLER    EV_OLED_CONTROLLER_SSD1306
#define EV_BOARD_RTC_SQW_LINE_ID    0U
#define EV_BOARD_RUNTIME_HARDWARE_PRESENT_MASK \
    (EV_SUPERVISOR_HW_MCP23008 | EV_SUPERVISOR_HW_RTC | EV_SUPERVISOR_HW_OLED | EV_SUPERVISOR_HW_DS18B20)
#define EV_BOARD_SUPERVISOR_REQUIRED_MASK \
    (EV_SUPERVISOR_HW_MCP23008 | EV_SUPERVISOR_HW_RTC)
#define EV_BOARD_SUPERVISOR_OPTIONAL_MASK \
    (EV_SUPERVISOR_HW_OLED | EV_SUPERVISOR_HW_DS18B20)

/*
 * Hardware-in-the-loop I2C zero-heap test policy.  Fault GPIOs are disabled by
 * default because they require an external open-drain-safe fixture wired to the
 * I2C bus or IRQ input.  Override these macros from the target build or board
 * lab profile only when the fixture is present.
 */
#ifndef EV_BOARD_HIL_I2C_RTC_READ_ITERATIONS
#define EV_BOARD_HIL_I2C_RTC_READ_ITERATIONS 1000U
#endif
#ifndef EV_BOARD_HIL_I2C_MCP_RW_ITERATIONS
#define EV_BOARD_HIL_I2C_MCP_RW_ITERATIONS 1000U
#endif
#ifndef EV_BOARD_HIL_I2C_OLED_PARTIAL_FLUSHES
#define EV_BOARD_HIL_I2C_OLED_PARTIAL_FLUSHES 16U
#endif
#ifndef EV_BOARD_HIL_I2C_OLED_FULL_FLUSHES
#define EV_BOARD_HIL_I2C_OLED_FULL_FLUSHES 1U
#endif
#ifndef EV_BOARD_HIL_I2C_IRQ_FLOOD_TRANSACTIONS
#define EV_BOARD_HIL_I2C_IRQ_FLOOD_TRANSACTIONS 128U
#endif
#ifndef EV_BOARD_HIL_I2C_MISSING_ADDR_7BIT
#define EV_BOARD_HIL_I2C_MISSING_ADDR_7BIT 0x55U
#endif
#ifndef EV_BOARD_HIL_I2C_SDA_FAULT_GPIO
#define EV_BOARD_HIL_I2C_SDA_FAULT_GPIO (-1)
#endif
#ifndef EV_BOARD_HIL_I2C_SCL_FAULT_GPIO
#define EV_BOARD_HIL_I2C_SCL_FAULT_GPIO (-1)
#endif
#ifndef EV_BOARD_HIL_IRQ_FLOOD_OUTPUT_GPIO
#define EV_BOARD_HIL_IRQ_FLOOD_OUTPUT_GPIO (-1)
#endif
#ifndef EV_BOARD_HIL_IRQ_FLOOD_LINE_ID
#define EV_BOARD_HIL_IRQ_FLOOD_LINE_ID 0U
#endif
#ifndef EV_BOARD_HIL_WIFI_CONNECT_TIMEOUT_MS
#define EV_BOARD_HIL_WIFI_CONNECT_TIMEOUT_MS 30000U
#endif
#ifndef EV_BOARD_HIL_WIFI_AP_LOSS_TIMEOUT_MS
#define EV_BOARD_HIL_WIFI_AP_LOSS_TIMEOUT_MS 60000U
#endif
#ifndef EV_BOARD_HIL_WIFI_RECOVERY_TIMEOUT_MS
#define EV_BOARD_HIL_WIFI_RECOVERY_TIMEOUT_MS 60000U
#endif
#ifndef EV_BOARD_HIL_WIFI_RECONNECT_STORM_WINDOW_MS
#define EV_BOARD_HIL_WIFI_RECONNECT_STORM_WINDOW_MS 10000U
#endif
#ifndef EV_BOARD_HIL_WIFI_MAX_RING_HIGH_WATERMARK
#define EV_BOARD_HIL_WIFI_MAX_RING_HIGH_WATERMARK 16U
#endif
#ifndef EV_BOARD_HIL_WIFI_MAX_HEAP_DELTA_BYTES
#define EV_BOARD_HIL_WIFI_MAX_HEAP_DELTA_BYTES 0U
#endif
#ifndef EV_BOARD_HIL_WIFI_MAX_RECONNECT_ATTEMPTS
#define EV_BOARD_HIL_WIFI_MAX_RECONNECT_ATTEMPTS 64U
#endif

#ifndef EV_BOARD_HIL_ONEWIRE_READS
#define EV_BOARD_HIL_ONEWIRE_READS 4U
#endif
#ifndef EV_BOARD_HIL_ONEWIRE_MAX_RESET_CRITICAL_US
#define EV_BOARD_HIL_ONEWIRE_MAX_RESET_CRITICAL_US 1250U
#endif
#ifndef EV_BOARD_HIL_ONEWIRE_MAX_BIT_CRITICAL_US
#define EV_BOARD_HIL_ONEWIRE_MAX_BIT_CRITICAL_US 120U
#endif

#endif /* EV_ATNEL_AIR_BOARD_PROFILE_H */
