COMPONENT_SRCDIRS := .
COMPONENT_ADD_INCLUDEDIRS := . ../../../../../bsp/atnel_air_esp_motherboard
COMPONENT_REQUIRES := ev_platform
CFLAGS += -DEV_HIL_I2C_ZERO_HEAP=1 \
    -DEV_BOARD_HIL_I2C_MISSING_ADDR_7BIT=0x7AU \
    -DEV_BOARD_HIL_I2C_SDA_FAULT_GPIO=12 \
    -DEV_BOARD_HIL_I2C_SCL_FAULT_GPIO=13 \
    -DEV_BOARD_HIL_IRQ_FLOOD_OUTPUT_GPIO=15 \
    -DEV_BOARD_HIL_IRQ_FLOOD_LINE_ID=0
